id: P007957
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:51:37.583349
source_metadata:
  id: bdr:W8LS20677
  title: བོད་སྐད་ཡིག་རྨང་གཞི་བསླབ་དེབ།
  author: ''
  volumes:
    1798f7dd79694c38bd6485e89031dc2b:
      image_group_id: I8LS20679
      title: Volume 1 of bod skad yig rmang gzhi bslab deb/
      volume_number: 1
      total_pages: 243
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
