id: P007957
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20677
  title: བོད་སྐད་ཡིག་རྨང་གཞི་བསླབ་དེབ།
  author: ''
  volumes:
    fbf0cad2b141485489684fa198f21d89:
      image_group_id: I8LS20679
      title: ''
      volume_number: 1
      total_pages: 243
ebook_metadata:
  title: བོད་སྐད་ཡིག་རྨང་གཞི་བསླབ་དེབ།
  author: ''
  sku: P007957
  cover: cover.jpg
  layers:
  - pagination
