id: I044BBDB3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:15:32+00:00'
last_modified: '2022-06-09T07:59:14.063566+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20677
  title: བོད་སྐད་ཡིག་རྨང་གཞི་བསླབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1EBB:
      image_group_id: I8LS20679
      title: Volume 1 of bod skad yig rmang gzhi bslab deb/
      total_pages: 243
      order: 1
      base_file: 1EBB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
